
pipeline_name: OCR

text_type: general

use_doc_preprocessor: True
use_textline_orientation: True

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    use_doc_orientation_classify: True
    use_doc_unwarping: True
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: null

SubModules:
  TextDetection:
    module_name: text_detection
    # PP-OCRv4_server_det
    # PP-OCRv4_mobile_det
    # PP-OCRv3_mobile_rec
    # PP-OCRv5_server_det
    model_name: PP-OCRv4_server_det
    model_dir: null
    limit_side_len: 960
    limit_type: max
    thresh: 0.3
    box_thresh: 0.6
    unclip_ratio: 2.0
  TextLineOrientation:
    module_name: textline_orientation
    model_name: PP-LCNet_x0_25_textline_ori 
    model_dir: null
    batch_size: 6    
  TextRecognition:
    module_name: text_recognition
    # PP-OCRv4_server_rec_doc
    # PP-OCRv4_mobile_rec
    # PP-OCRv4_server_rec
    # en_PP-OCRv4_mobile_rec
    # korean_PP-OCRv3_mobile_rec
    model_name: korean_PP-OCRv3_mobile_rec
    # model_dir: output/pho_rec/train_gpu2_ep8_bs256_lr1e-3/best_accuracy/inference
    # model_dir: output/pho_rec/train_gpu0_ep8_bs256_lr1e-4/best_accuracy/inference
    model_dir: output/pho_rec/train_gpu1_ep8_bs256_lr1e-5/best_accuracy/inference
    batch_size: 6
    score_thresh: 0.0
